net-il-mio-fotoalbum/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using net_il_mio_fotoalbum.CustomLoggers;
using net_il_mio_fotoalbum.Database;
using net_il_mio_fotoalbum.Models;
using net_il_mio_fotoalbum.Models.Database_Models;

namespace net_il_mio_fotoalbum.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class CategoryController : Controller
    {

        private ICustomLogger _myLogger;
        private FotoalbumContext _myDatabase;

        public CategoryController(FotoalbumContext db, ICustomLogger logger)
        {
            _myDatabase = db;
            _myLogger = logger;
        }

        public IActionResult Index()
        {
            _myLogger.WriteLog("L'utente è arrivato sulla pagina Category > Index");

            List<Category>? categories = _myDatabase.Categories.ToList<Category>();

            return View("Index", categories);
        }

        public IActionResult Details(int id)
        {
            _myLogger.WriteLog("L'utente è arrivato sulla pagina Category > Details");

            Category? foundedCategory = _myDatabase.Categories.Where(category => category.Id == id).FirstOrDefault();

            if (foundedCategory == null)
            {
                return NotFound($"La categoria {id} non è stata trovata!");
            }
            else
            {
                return View("Details", foundedCategory);
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            _myLogger.WriteLog("L'utente è arrivato sulla pagina Category > Create");

            Category newCategory = new Category();

            return View("Create", newCategory);
        }

     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            _myDatabase.Categories.Add(category);
            _myDatabase.SaveChanges();

            return RedirectToAction("Index");
        }

        
        [Authorize(Roles = "ADMIN")]
        [HttpGet]
        public IActionResult Update(int id)
        {
            Category? categoryToEdit = _myDatabase.Categories.Where(category => category.Id == id).FirstOrDefault();

            if (categoryToEdit == null)
            {
                return NotFound("La categoria che vuoi modificare non è stata trovata");
            }
            else
            {
                _myLogger.WriteLog("L'utente è arrivato sulla pagina Category > Update");

                Category category = categoryToEdit;

                return View("Update", category);
            }
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, Category category)
        {

            Category? categoryToUpdate = _myDatabase.Categories.Where(category => category.Id == id).FirstOrDefault();

            if (categoryToUpdate != null)
            {
                categoryToUpdate.Name = category.Name;

                _myDatabase.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return NotFound("Attenzione non è stata trovata la categoria da aggiornare");
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {

            Category? categoryToDelete = _myDatabase.Categories.Where(category => category.Id == id).FirstOrDefault();

            if (categoryToDelete != null)
            {
                _myDatabase.Categories.Remove(categoryToDelete);
                _myDatabase.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return NotFound("La categoria da eliminare non è stata trovata!");
            }
        }

    }

}    

net-il-mio-fotoalbum/Controllers/MessagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using net_il_mio_fotoalbum.CustomLoggers;
using net_il_mio_fotoalbum.Database;
using net_il_mio_fotoalbum.Models.Database_Models;

namespace net_il_mio_fotoalbum.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class MessagesController : Controller
    {

        private ICustomLogger _myLogger;

        private FotoalbumContext _myDatabase;

        public MessagesController(FotoalbumContext db, ICustomLogger logger)
        {
            _myDatabase = db;
            _myLogger = logger;
        }

        public IActionResult Index()
        {
            _myLogger.WriteLog("L'utente è arrivato sulla pagina Messages > Index");

            List<Message> messages = _myDatabase.Messages.ToList<Message>();

            return View("Index",messages);
        }

        public IActionResult Details(int id)
        {
            _myLogger.WriteLog("L'utente è arrivato sulla pagina Messages > Details");

            Message? foundedMessage = _myDatabase.Messages.Where(message => message.Id == id).FirstOrDefault();

            if (foundedMessage == null)
            {
                return NotFound($"Il messaggio {id} non è stato trovato!");
            }
            else
            {
                return View("Details", foundedMessage);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {

            Message? messageToDelete = _myDatabase.Messages.Where(message => message.Id == id).FirstOrDefault();

            if (messageToDelete != null)
            {
                _myDatabase.Messages.Remove(messageToDelete);
                _myDatabase.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return NotFound("Il messaggio da eliminare non è stato trovato!");
            }
        }
    }
    
}

net-il-mio-fotoalbum/Views/Shared/_Footer.cshtml
<footer class="py-4 border-top d-flex justify-content-between align-items-center">
    <div class="d-flex justify-content-center align-items-end">
        <img src="~/img/logo-album.jpg" class="logo me-4" alt="Immagine logo" />
        <p class="fw-bold text-color">Il mio Foto Album</p>
    </div>
    <ul class="nav col-md-4 d-flex justify-content-between">
        <li class="nav-item"><a href="#" class="nav-link px-2 fw-bold">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 fw-bold">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 fw-bold">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 fw-bold">FAQs</a></li>
        <li class="nav-item me-2"><a href="#" class="nav-link px-2 fw-bold">About</a></li>
    </ul>
</footer>

net-il-mio-fotoalbum/Views/Shared/_Header.cshtml
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary py-3">
        <div class="container-fluid">
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-lg-0 d-flex justify-content-center align-items-start">
                    <li>
                        <a class="navbar-brand fw-bold text-color fs-3" href="@Url.Action("Index", "Fotoalbum")">Il mio Foto Album</a>
                    </li>
                    <li>
                        <a class="nav-link  text-primary fw-bold fs-5" href="@Url.Action("Index", "Category")">Categorie foto</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-primary fw-bold fs-5" href="@Url.Action("Index", "Messages")">Messaggi</a>
                    </li>
                    <li>
                        <a class="nav-link text-primary fw-bold fs-5" href="@Url.Action("Index", "Home")">Utente</a>
                    </li>

                    <div class="ms-5 mt-1">
                        <partial name="_LoginPartial" />
                    </div>
                </ul>

                <div class="fs-5">
                    <button class="button-user"><a class="nav-link text-secondary fw-bold" href='http://localhost:5174/'> Sito Utente </a></button>
                </div>

            </div>
        </div>
    </nav>

</header>

net-il-mio-fotoalbum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - net_il_mio_fotoalbum</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
   
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    
    @RenderSection("Style", required: false)
</head>
<body>

    @Html.Partial("_Header")


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    @(await Html.PartialAsync("_Footer"))

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- importo bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <!-- importo axios -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.5.1/axios.min.js" integrity="sha512-emSwuKiMyYedRwflbZB2ghzX8Cw8fmNVgZ6yQNNXXagFzFOaQmbvQ1vmDkddHjm5AITcBIZfC7k4ShQSjgPAmQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <script src="~/js/site.js" asp-append-version="true"></script>

    @(await RenderSectionAsync("Scripts", required: false))
</body>
</html>

net-il-mio-fotoalbum/Views/Shared/_LayoutCategory.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - net_il_mio_fotoalbum</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    @RenderSection("StyleCategory", required: false)
</head>
<body>

    @Html.Partial("_Header")


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    @(await Html.PartialAsync("_Footer"))

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- importo bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  

    <script src="~/js/site.js" asp-append-version="true"></script>

    @(await RenderSectionAsync("Scripts", required: false))
</body>
</html>

net-il-mio-fotoalbum/Views/Shared/_LayoutDetails.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - net_il_mio_fotoalbum</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    @RenderSection("StyleDetails", required: false)
</head>
<body>

    @Html.Partial("_Header")


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    @(await Html.PartialAsync("_Footer"))

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- importo bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <!-- importo axios -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.5.1/axios.min.js" integrity="sha512-emSwuKiMyYedRwflbZB2ghzX8Cw8fmNVgZ6yQNNXXagFzFOaQmbvQ1vmDkddHjm5AITcBIZfC7k4ShQSjgPAmQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @(await RenderSectionAsync("Scripts", required: false))
</body>
</html>

net-il-mio-fotoalbum/Views/Shared/_LayoutError.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - net_il_mio_fotoalbum</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    @RenderSection("StyleError", required: false)
</head>
<body>

    @Html.Partial("_Header")


  
</body>
</html>

net-il-mio-fotoalbum/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizzeria Statica</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @RenderSection("StyleLogin", required: false)
</head>
<body>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @(await RenderSectionAsync("Scripts", required: false))
</body>
</html>

net-il-mio-fotoalbum/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - net_il_mio_fotoalbum</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    @RenderSection("StyleUser", required: false)
</head>
<body>

  


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


   

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- importo bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <!-- importo axios -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.5.1/axios.min.js" integrity="sha512-emSwuKiMyYedRwflbZB2ghzX8Cw8fmNVgZ6yQNNXXagFzFOaQmbvQ1vmDkddHjm5AITcBIZfC7k4ShQSjgPAmQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @(await RenderSectionAsync("Scripts", required: false))
</body>
</html>